name: PHP Library

on:
  workflow_call:
    inputs:
      checks:
        description: |
          List of enabled check separated by comma.
          default: phpunit,phpcs,psalm
          available checks: phpunit,phpcs,psalm
        required: false
        default: "phpunit,phpcs,psalm"
        type: string
      report-retention-days:
        description: "Duration in days to preserve reports."
        required: false
        default: "5"
        type: string
      working-directory:
        description: "Workflow working directory"
        default: '.'
        required: false
        type: string
      php-version:
        description: 'Setup PHP version.'
        default: '7.4'
        required: false
        type: string
      extensions:
        description: 'Setup PHP extensions.'
        required: false
        type: string
    secrets:
      GPR_KEY:
        description: Personal access token to fetch private repos
        required: false

env:
  php-cache-key: v1

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    if: contains(inputs.checks, 'phpunit')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: equisoft-actions/setup-php@v1.1.0
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          cache-key: ${{ env.php-cache-key }}

      - name: Composer install
        uses: equisoft-actions/composer@v1.1.0
        with:
          gpr-key: ${{ secrets.GPR_KEY}}
          working-directory: ${{ inputs.working-directory }}

      - name: PHPUnit
        uses: equisoft-actions/phpunit@v0.0.3
        with:
          working-directory: ${{ inputs.working-directory }}
          report-retention-days: ${{ inputs.report-retention-days }}

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    if: contains(inputs.checks, 'psalm')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: equisoft-actions/setup-php@v1.1.0
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          cache-key: ${{ env.php-cache-key }}

      - name: Composer install
        uses: equisoft-actions/composer@v1.1.0
        with:
          gpr-key: ${{ secrets.GPR_KEY}}
          working-directory: ${{ inputs.working-directory }}

      - name : Psalm
        uses : equisoft-actions/psalm@d20b22f986d0f3fa555f9e67e3f14e0f1f874570
        with:
          working-directory: ${{ inputs.working-directory }}
          default-branch: master
          extra-args: --no-cache --no-diff

  phpcs:
    name: PHP_Codesniffer
    runs-on: ubuntu-latest
    if: contains(inputs.checks, 'phpcs')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: equisoft-actions/setup-php@v1.1.0
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          cache-key: ${{ env.php-cache-key }}

      - name: Composer install
        uses: equisoft-actions/composer@v1.1.0
        with:
          gpr-key: ${{ secrets.GPR_KEY}}
          working-directory: ${{ inputs.working-directory }}

      - name : PHP_Codesniffer
        uses : equisoft-actions/phpcs@c9b6f943ab5ed3a4abee0d624df104cd608861a7
        with:
          default-branch: master
          working-directory: ${{ inputs.working-directory }}
          report-retention-days: ${{ inputs.report-retention-days }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - psalm
      - phpunit
      - phpcs
    if: failure() && github.event_name == 'push'
    steps:
      - name: Post workflow status
        uses: kronostechnologies/actions/notify-workflow-status@v0.0.23
        with:
          needs: ${{ toJSON(needs) }}
          slack-webhook-url: ${{ secrets.OPS_CI_WEBHOOK_URL }}
