name: psalm taint analysis

on:
  workflow_call:
    inputs:
      report-retention-days:
        description: "Duration in days to preserve reports."
        required: false
        default: "5"
        type: string
      working-directory:
        description: "Workflow working directory"
        default: '.'
        required: false
        type: string
      php-version:
        description: 'Setup PHP version.'
        default: '7.4'
        required: false
        type: string
      extensions:
        description: 'Setup PHP extensions.'
        required: false
        type: string
      defectdojo-publish:
        description: "Publish sarif report to defectdojo"
        default: false
        required: false
        type: boolean
      defectdojo-url:
        description: "DefectDojo URL"
        default: ''
        required: false
        type: string
      defectdojo-engagement:
        description: "DefectDojo Engagement name or id"
        default: ''
        required: false
        type: string
    secrets:
      gpr-key:
        description: Personal access token to fetch private repos
        required: false
      defectdojo-token:
        description: DefectDojo API Token
        required: false

jobs:
  psalm-taint-analysis:
    name: psalm taint analysis
    runs-on: ubuntu-latest
    env:
      cache-key: v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: equisoft-actions/setup-php@v1.0.0
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          cache-key: ${{ env.cache-key }}

      - name: Composer install
        uses: equisoft-actions/composer@v1.0.0
        with:
          gpr-key: ${{ secrets.gpr-key }}
          working-directory: ${{ inputs.working-directory }}

      - name: Taint analysis
        uses: equisoft-actions/psalm-taint-analysis@3ba2179bce6b65af002299a97e09094f44667d0e
        with:
          working-directory: ${{ inputs.working-directory }}
          report-retention-days: ${{ inputs.report-retention-days }}
          defectdojo-publish: ${{ inputs.defectdojo-publish }}
          defectdojo-url: ${{ inputs.defectdojo-url }}
          defectdojo-engagement: ${{ inputs.defectdojo-engagement }}
          defectdojo-token: ${{ secrets.defectdojo-token }}
