name: psalm taint analysis

on:
  workflow_call:
    inputs:
      report-retention-days:
        description: "Duration in days to preserve reports."
        required: false
        default: "5"
        type: string
      working-directory:
        description: "Workflow working directory"
        default: '.'
        required: false
        type: string
      php-version:
        description: 'Setup PHP version.'
        default: '8.1'
        required: true
        type: string
      extensions:
        description: 'Setup PHP extensions.'
        required: false
        type: string
    secrets:
      gpr-key:
        description: Personal access token to fetch private repos
        required: false

jobs:
  psalm-taint-analysis:
    name: psalm taint analysis
    runs-on: ubuntu-latest
    env:
      cache-key: v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}
          key: ${{ env.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.extensions }}

      - name: Composer install
        uses: equisoft-actions/composer@v1.0.0
        with:
          gpr-key: ${{ secrets.gpr-key }}
          working-directory: ${{ inputs.working-directory }}

      - name: Taint analysis
        uses: equisoft-actions/psalm-taint-analysis@a3fd7897364efdfb78d8d4dc826dc9753df92a0b
        with:
          working-directory: ${{ inputs.working-directory }}
          report-retention-days: ${{ inputs.report-retention-days }}
